
#include "globals.h"
#include <complex.h>

void ffind_fourier_transfer_function(double *ptime_samples,double *pphasein_samples,double *pphaseo_samples,double *pphaseo_delayed_samples,long int number_of_samples,double fj,Filedata *pdatain,double *gain_at_fin_in_dB,double *phase_at_fin_rad, char *pfileout)
{
/*This routine reads the text file generated by this program and computes the peak-to-peak value and average of
phasein, phaseo, and phaseo_delayed. It then subtracts the average value from each and recomputes their 
zero-mean values and places the result in file pointed to by pfileout*/

/* It computes the Fourier magnitude of phasein, phaseo, and phaseo_delayed at the jitter frequency
to determine the transfer function phaseo/phasein at fj and places the result in *gain_at_fin_in_dB and
*phase_at_fin_rad */

long int i = 0, phaseo_delayed_column_number = 0;
static int num_jitter_freq = 1;

char tempstring1[CSV_FILE_LINELENGTH + 1], *ptempstring1;
char tempstring2[CSV_FILE_LINELENGTH + 1], *ptempstring2;
char tempstring3[CSV_FILE_LINELENGTH + 1], *ptempstring3;
char *plog_string,log_string[LOGFILE_LINELENGTH + 1];
char value_string[NUMBER_OF_VALUE_STRINGS][LINELENGTH_OF_VALUE_STRING + 1];

double deltat = EPSILON, sum_deltat = 0.0, N = 0.0;
double phasein_max = -1.0, phasein_min = +1.0, phaseo_max = -1.0, phaseo_min = 1.0;
double phaseo_delayed_max = -1.0, phaseo_delayed_min = 1.0;
double phasein = 0.0, phaseo = 0.0, phaseo_delayed = 0.0;
double phasein_DC = 0.0, phaseo_DC = 0.0, phaseo_delayed_DC = 0.0;
double ampjitterin_pp = 0.0, ampjitterout_pp = 0.0;
double ampjitterout_delayed_pp = 0.0;
double K = 0.0, gamma = 0.0;
double mag = 0.0, magm1 = 0.0, magp1 = 0.0;
double mag_delayed, magm1_delayed = 0.0, magp1_delayed = 0.0;
double magin = 0.0, maginm1 = 0.0, maginp1 = 0.0;
double output_phase_at_fin_rad = 0.0, output_delayed_phase_at_fin_rad = 0.0;
double input_phase_at_fin_rad = 0.0, relative_phase_at_fin_rad = 0.0, relative_delayed_phase_at_fin_rad = 0.0;
double relative_gain_at_fin_in_dB = 0.0, relative_delayed_gain_at_fin_in_dB = 0.0;
double zeta, zeta_m1, zeta_p1;

double complex exp_const = 0.0 + 0.0i;
double complex z_phaseo = 0.0 + 0.0i, z_phasein = 0.0 + 0.0i, z_phaseo_delayed = 0.0 + 0.0i;
double complex z_phaseo_m1 = 0.0 + 0.0i, z_phasein_m1 = 0.0 + 0.0i, z_phaseo_delayed_m1 = 0.0 + 0.0i;
double complex z_phaseo_p1 = 0.0 + 0.0i, z_phasein_p1 = 0.0 + 0.0i, z_phaseo_delayed_p1 = 0.0 + 0.0i;

FILE *fpw1;

ptempstring1 = &tempstring1[0];
ptempstring2 = &tempstring2[0];
ptempstring3 = &tempstring3[0];
plog_string = &log_string[0];

#ifdef SAVE_POST_PROCESSED_FILE
	fpw1 = fopen(pfileout,"w");
	fprintf(fpw1,"Time (s),phasein (UI),phaseo (UI),phaseo - phasein (UI),phaseo_delayed (UI),phaseo_delayed - phasein (UI)\n");
#endif

phasein_max = max(pphasein_samples,number_of_samples);
phasein_min = min(pphasein_samples,number_of_samples);
phasein_DC = mean(pphasein_samples,number_of_samples);

phaseo_max = max(pphaseo_samples,number_of_samples);
phaseo_min = min(pphaseo_samples,number_of_samples);
phaseo_DC = mean(pphaseo_samples,number_of_samples);

phaseo_delayed_max = max(pphaseo_delayed_samples,number_of_samples);
phaseo_delayed_min = min(pphaseo_delayed_samples,number_of_samples);
phaseo_delayed_DC = mean(pphaseo_delayed_samples,number_of_samples);

for (i = 1; i < number_of_samples; i++)
	sum_deltat = sum_deltat + ptime_samples[i] - ptime_samples[i-1];
	
deltat = sum_deltat/((double) (number_of_samples - 1));

/* snprintf(plog_string,LOGFILE_LINELENGTH,
"jitter transfer analysis delta =  %s (analysis deltat = %s).\n",
add_units(deltat,3,"s",value_string[0]),
add_units(pdatain->deltat,3,"s",value_string[1]));
print_string_to_log(plog_string,pdatain); */
	
/*Compute and print maximum and minimum values, write to new file*/

snprintf(plog_string,LOGFILE_LINELENGTH,
"phasein_min = %s, phasein_max = %s.\n",
add_units(phasein_min,3,"UI",value_string[0]),
add_units(phasein_max,3,"UI",value_string[1]));
ampjitterin_pp = phasein_max - phasein_min;
print_string_to_log(plog_string,pdatain);

snprintf(plog_string,LOGFILE_LINELENGTH,
"DC average removed from phasein is %s.\n",
add_units(phasein_DC,1,"UI",value_string[0]));
print_string_to_log(plog_string,pdatain);

snprintf(plog_string,LOGFILE_LINELENGTH,
"Input jitter amplitude = %s\n",
add_units(ampjitterin_pp,1,"UIpp",value_string[0]));
print_string_to_log(plog_string,pdatain);

snprintf(plog_string,LOGFILE_LINELENGTH,
"phaseo_min = %s, phaseo_max = %s.\n",
add_units(phaseo_min,3,"UI",value_string[0]),
add_units(phaseo_max,3,"UI",value_string[1]));
print_string_to_log(plog_string,pdatain);

ampjitterout_pp = phaseo_max - phaseo_min;

snprintf(plog_string,LOGFILE_LINELENGTH,
"DC average removed from phaseo is %s.\n",
add_units(phaseo_DC,3,"UI",value_string[0]));
print_string_to_log(plog_string,pdatain);

snprintf(plog_string,LOGFILE_LINELENGTH,
"phaseo jitter amplitude = %s\n",
add_units(ampjitterout_pp,1,"UIpp",value_string[0]));
print_string_to_log(plog_string,pdatain);

snprintf(plog_string,LOGFILE_LINELENGTH,
"phaseo_delayed_min = %s, phaseo_delayed_max = %s.\n",
add_units(phaseo_delayed_min,3,"UI",value_string[0]),
add_units(phaseo_delayed_max,3,"UI",value_string[1]));
print_string_to_log(plog_string,pdatain);

ampjitterout_delayed_pp = phaseo_delayed_max - phaseo_delayed_min;
snprintf(plog_string,LOGFILE_LINELENGTH,
"DC average removed from phaseo_delayed is %s.\n",
add_units(phaseo_delayed_DC,3,"UI",value_string[0]));
print_string_to_log(plog_string,pdatain);
snprintf(plog_string,LOGFILE_LINELENGTH,
"phaseo_delayed jitter amplitude = %s\n",
add_units(ampjitterout_delayed_pp,1,"UIpp",value_string[0]));
print_string_to_log(plog_string,pdatain);

/*For analysis at fj, K and gamma are found as follows*/

gamma = (2.0 * pi)/((((double) number_of_samples) - 1.0)*deltat);
K = 2.0 * pi * fj/gamma;

zeta = gamma * K * deltat;
zeta_m1 = gamma * (K - 1.0) * deltat;
zeta_p1 = gamma * (K + 1.0) * deltat;

for (i = 0; i < number_of_samples; i++)
   {
   pphasein_samples[i] = pphasein_samples[i] - phasein_DC;
   pphaseo_samples[i] = pphaseo_samples[i] - phaseo_DC;
   pphaseo_delayed_samples[i] = pphaseo_delayed_samples[i] - phaseo_delayed_DC;
   
   /* Compute fourier component of phaseo */
   
   z_phaseo_m1 += pphaseo_samples[i] * cexp(zeta_m1*N*I);
   z_phaseo += pphaseo_samples[i] * cexp(zeta*N*I);
   z_phaseo_p1 += pphaseo_samples[i] * cexp(zeta_p1*N*I);

   /* Compute fourier component of pphaseo_delayed */
   
   z_phaseo_delayed_m1 += pphaseo_delayed_samples[i] * cexp(zeta_m1*N*I);
   z_phaseo_delayed += pphaseo_delayed_samples[i] * cexp(zeta*N*I);
   z_phaseo_delayed_p1 += pphaseo_delayed_samples[i] * cexp(zeta_p1*N*I);
   
   /* Compute fourier component of pphasein */
   
   z_phasein_m1 += + pphasein_samples[i] * cexp(zeta_m1*N*I);
   z_phasein += pphasein_samples[i] * cexp(zeta*N*I);
   z_phasein_p1 += pphasein_samples[i] * cexp(zeta_p1*N*I);
   
   /* Print phase data results to file */
   
	#ifdef SAVE_POST_PROCESSED_FILE
   	fprintf(fpw1,"%1.12e,%1.12e,%1.12e,%1.12e,%1.12e,%1.12e\n",
   	ptime_samples[i], pphasein_samples[i], pphaseo_samples[i], pphaseo_samples[i] - pphasein_samples[i],
   	pphaseo_delayed_samples[i], pphaseo_delayed_samples[i] - pphasein_samples[i]);
   #endif
   
   N = N + 1.0;
   }
   /* snprintf(plog_string,LOGFILE_LINELENGTH,
	"real = %1.12e, imag = %1.12e, phase = %1.4e degrees\n",cimag(z_phaseo),creal(z_phaseo),(180.0/pi)*carg(1.0/z_phaseo));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"real_delayed = %1.12e, imag_delayed = %1.12e, phase = %1.4e degrees\n",cimag(z_phaseo_delayed),creal(z_phaseo_delayed),(180.0/pi)*carg(1.0/z_phaseo_delayed));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"zr = %1.12e, zi = %1.12e, phase = %1.4e degrees\n",cimag(z_phasein),creal(z_phasein),(180.0/pi)*carg(1.0/z_phasein));
	print_string_to_log(plog_string,pdatain); */

/*Compute the fourier output magnitude at fundamental output and either side of it*/

mag = cabs(z_phaseo);
magm1 = cabs(z_phaseo_m1);
magp1 = cabs(z_phaseo_p1);

mag_delayed = cabs(z_phaseo_delayed);
magm1_delayed = cabs(z_phaseo_delayed_m1);
magp1_delayed = cabs(z_phaseo_delayed_p1);

/*Compute the fourier input magnitude at fundmental output and either side of it*/

magin = cabs(z_phasein);
maginm1 = cabs(z_phasein_m1);
maginp1 = cabs(z_phasein_p1);

relative_phase_at_fin_rad = carg(z_phasein/z_phaseo);
relative_delayed_phase_at_fin_rad = carg(z_phasein/z_phaseo_delayed);

if (pdatain->D_delay > 0.0 + EPSILON)
	*phase_at_fin_rad = relative_delayed_phase_at_fin_rad;
else
	*phase_at_fin_rad = relative_phase_at_fin_rad;

/*If energy on either side is a factor 10 less than fundamental, compute jitter transfer*/
/*Otherwise - have user check output file to make sure tracking is satisfactory*/

if ((magm1 < 10.0 * mag) && (magp1 < 10.0 * mag))
   {
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"phasein magnitude = %2.6f, phaseo magnitude = %2.6f\n",cabs(z_phasein),cabs(z_phaseo));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"At Aj = %s,fj = %s, jitter transfer function = %2.3f dB.\n",
   add_units(ampjitterin_pp,1,"UIpp",value_string[0]),
   add_units(fj,3,"Hz",value_string[1]),20.0*log10(cabs(z_phaseo/z_phasein)));
   print_string_to_log(plog_string,pdatain);
   
	relative_gain_at_fin_in_dB = 20.0*log10(cabs(z_phaseo/z_phasein));

	snprintf(plog_string,LOGFILE_LINELENGTH,
	"phasein magnitude = %2.6f, phaseo_delayed magnitude = %2.6f\n",cabs(z_phasein),cabs(z_phaseo_delayed));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"At Aj = %s,fj = %s, jitter transfer function = %2.3f dB.\n",
   add_units(ampjitterin_pp,1,"UIpp",value_string[0]),
   add_units(fj,3,"Hz",value_string[1]),20.0*log10(cabs(z_phaseo_delayed/z_phasein)));
   print_string_to_log(plog_string,pdatain);
   
   relative_delayed_gain_at_fin_in_dB = 20.0*log10(cabs(z_phaseo_delayed/z_phasein));

   }
else
   {
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"Check tracking...\n");
	print_string_to_log(plog_string,pdatain);
	
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"phasein magnitude = %2.6f, phaseo magnitude = %2.6f\n",
	cabs(z_phasein),cabs(z_phaseo));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"At Aj = %s,fj = %s, jitter transfer function = %2.3f dB.\n",
   add_units(ampjitterin_pp,1,"UIpp",value_string[0]),
   add_units(fj,3,"Hz",value_string[1]),20.0*log10(cabs(z_phaseo/z_phasein)));
   print_string_to_log(plog_string,pdatain);
   
   relative_gain_at_fin_in_dB = 20.0*log10(cabs(z_phaseo/z_phasein));
   
	snprintf(plog_string,LOGFILE_LINELENGTH,
	"phasein magnitude = %2.6f, phaseo_delayed magnitude = %2.6f\n",
	cabs(z_phasein),cabs(z_phaseo_delayed));
	print_string_to_log(plog_string,pdatain);
   snprintf(plog_string,LOGFILE_LINELENGTH,
	"At Aj = %s,fj = %s, jitter transfer function = %2.3f dB.\n",
   add_units(ampjitterin_pp,1,"UIpp",value_string[0]),
   add_units(fj,3,"Hz",value_string[1]),20.0*log10(cabs(z_phaseo_delayed/z_phasein)));
   print_string_to_log(plog_string,pdatain);
	
	relative_delayed_gain_at_fin_in_dB = 20.0*log10(cabs(z_phaseo_delayed/z_phasein));

   }

if (pdatain->D_delay > 0.0 + EPSILON)
	*gain_at_fin_in_dB = relative_delayed_gain_at_fin_in_dB;
else
	*gain_at_fin_in_dB = relative_gain_at_fin_in_dB;

#ifdef SAVE_POST_PROCESSED_FILE
	fclose(fpw1);
#endif

num_jitter_freq++;

return;
}
